### ISSUE TITLE
Allow to check multi-level subdomains

### ISSUE THREAD

**Issue by ewypych** [ewypych/icinga-domain-expiration-plugin#14]
Now there is no option to monitor multi-level subdomains like

`mail.com.ua`

but it would be good to allow that.

**Comment by BuildTheRobots** [comment]
there's also the very common ".co.uk" UK domain name.
I hacked in support for .uk and .co.uk as I needed it working with no time to spare,  but it's a pretty horrible way of doing it and could be done better:

https://github.com/BuildTheRobots/icinga-domain-expiration-plugin/blob/add_uk_co-uk_domain_checks/check_domain_expiration.sh

**Comment by ewypych** [comment]
Yeah, you're right @BuildTheRobots , it's very interesting why I did that script in that way. I even know what I should change to allow checking multi-level domains like `.co.uk` or even `.com.pl` (also very common in Poland). 

I'll try to do that this week, as it's not a complicated change. :) Also I'll try to add at the same time #17
